### ISSUE TITLE
Does't work with my BTG account

### ISSUE THREAD

**Issue by mjniuz** [Ayms/bitcoin-transactions#1] opened 2017-11-25 08:36 UTC
Hii

I have this transaction id 2fc6aff69c9707b264a1a01b6ba4dac69da497854dfb7ba67000fa9afcc8a3a2 [https://btgexp.com/tx/2fc6aff69c9707b264a1a01b6ba4dac69da497854dfb7ba67000fa9afcc8a3a2](url)

And this is my command line
`node tx.js BTG create prevtx=2fc6aff69c9707b264a1a01b6ba4dac69da497854dfb7ba67000fa9afcc8a3a2 prevaddr=GMx7vEPtYZvtS6AW7JEeFG18WCEDx2sZ9u prevamount=1.02668204 previndex=2 privkey=privkey addr=GMx7vEPtYZvtS6AW7JEeFG18WCEDx2sZ9u amount=0.0005`

Then i got response body, and start the request
`node tx.js BTG send e1476d44747800000000000000000000e200000094cd8b200200000001a2a3c8fc9afa0070a67bfb4d8597a49dc6daa46b1ba0a164b207979cf6afc62f020000006b483045022100f071a26b42106143f08648fc0332c57fd99c76c66061fbebcbe682a484c22b650220488eba44b9c95f55fb03ae2f90289051adc4924b80b5c88a4674062f007d3d2e412103328ba6c70c404497a663505914704a7b695331569d729745baa1f1cdcbf2d359ffffffff0250c30000000000001976a9142d0c99a1ff56f5856131016b5ade5b13e209885988ac34210000000000001976a9145b79a9d29a34f2f284ecdd33009ffa5e0252b68988ac00000000 79.124.17.202`

But nothing happen, my transaction still have the same confirmation number

Thankyou

**Comment by Ayms** [comment] 2017-11-25 11:33
Take care (!!!!)

It is mandatory that amount+dev fees+network fees=prevamount

Happier this one did not work, you must check:

Size 250 bytes
Network Fees: 102609704 - 410438.82 satoshis/byte
Dev Fees: 8500

In your case you are sending 1.026 BTG as network fees, that's maybe why it was rejected

I will modify the code so this can't happen, this module allows you to choose your fees so I cannot add some mechanisms to refund your address if you make a mistake with the fees

**Comment by Ayms** [comment] 2017-11-25 13:12
Please see https://github.com/Ayms/bitcoin-transactions/commit/e67cb06df6a05c4a0d42ac0f92b8fd7d0c587c92

Warnings/checks added

Closing it for now, please let me know if the problem is still there and then thanks for posting the logs

**Closed as completed by Ayms** 2017-11-25 13:12 UTC

**Comment by Ayms** [comment] 2017-11-28 18:04
Please see https://github.com/Ayms/bitcoin-transactions/issues/2#issuecomment-347609803 and the updated repo

Your transaction did not work (happily) because there was a mistake with the signatures in some cases

This is corrected, testamount feature added, fees parameter to choose your fees added too and people can know spend a part of the output as you tried to do and get refunded
