### ISSUE TITLE
TX decode failed. Code:-22

### ISSUE THREAD

**Issue by ianpurton** [Ayms/bitcoin-transactions#30] opened 2018-03-08 06:34 UTC
I'm trying to create a Bitcoin Private BTCD transaction. 

When I try to send the transaction using https://explorer.btcprivate.org/tx/send I get the error above.

![error](https://user-images.githubusercontent.com/36966/37136685-eeb3ec3a-22a2-11e8-9bf0-9e5807cc2be8.PNG)

UTXO information available ere https://explorer.btcprivate.org/address/b1H4VhwWAoVGMqnXM8oqsKK2WzpMGkbRamm

I run the following

`node tx.js BTCP create prevtx=db832d5b046eb2a297d2f3044c22a891d9c4adb9806396e39e1ec2cf531c0375 \
prevaddr=b1H4VhwWAoVGMqnXM8oqsKK2WzpMGkbRamm \
prevamount=0.005 previndex=0 \
privkey=REMOVED b19nP23vNEyWiyz6B9G5hFnt7w12RAPbsU9 fees=0.0000030`

I get the following output from tx.js

Version BTCP
Destination address b19nP23vNEyWiyz6B9G5hFnt7w12RAPbsU9
--- Prevamount is small, min dev fees of 17000 apply - amount should be 0.00482700
--- Previous amount is: 0.00500000
--- Amount to spend is: 0.00482700
--- Network fees are: 0.00000300
--- Dev fees are: 0.00017000
true
Using standard signing
Address corresponding to private key is b1H4VhwWAoVGMqnXM8oqsKK2WzpMGkbRamm
----- Transaction hash: 9657fbb131ad4c41519fe231833ed6697dcdb8f906e508179a7e7ec4de03f9c5
Transaction body:
020000000175031c53cfc21e9ee3966380b9adc4d991a8224c04f3d297a2b26e045b2d83db000000006a4730440220157fdca183bc7001fd7ac064706454cea8a120d65e17dced976b036b09447b6a022078bff8b4f280e91afee6ffa429f6ed0f9645b49b7d9499b6b734263338316637412103e131d6f9e9f83cfa18de2e89887cc4c829ab99c230bc884c22ddb6ffab19e121ffffffff028b5d0700000000001976a9143a48bfebcdc52c7b3831eab75a1955e58744c7e388ac68420000000000001976a9145b79a9d29a34f2f284ecdd33009ffa5e0252b68988ac00000000
Complete transaction:
a8eaa2cd747800000000000000000000e10000009657fbb1020000000175031c53cfc21e9ee3966380b9adc4d991a8224c04f3d297a2b26e045b2d83db000000006a4730440220157fdca183bc7001fd7ac064706454cea8a120d65e17dced976b036b09447b6a022078bff8b4f280e91afee6ffa429f6ed0f9645b49b7d9499b6b734263338316637412103e131d6f9e9f83cfa18de2e89887cc4c829ab99c230bc884c22ddb6ffab19e121ffffffff028b5d0700000000001976a9143a48bfebcdc52c7b3831eab75a1955e58744c7e388ac68420000000000001976a9145b79a9d29a34f2f284ecdd33009ffa5e0252b68988ac00000000
Size 249 bytes
Network Fees: 301 - 1.21 satoshis/byte
Dev Fees: 17000
------------- Check - deserialize 
Tx {
  input: 
   [ { hash: 'db832d5b046eb2a297d2f3044c22a891d9c4adb9806396e39e1ec2cf531c0375',
       n: 0,
       scriptSigLen: 106,
       scriptSig: [Object],
       script: [Object],
       nSequence: <Buffer ff ff ff ff> } ],
  output: 
   [ { nValue: 482699,
       scriptPubkeyLen: <Buffer 19>,
       scriptPubkey: <Buffer 76 a9 14 3a 48 bf eb cd c5 2c 7b 38 31 ea b7 5a 19 55 e5 87 44 c7 e3 88 ac>,
       address: 'b19nP23vNEyWiyz6B9G5hFnt7w12RAPbsU9',
       type: 'p2pkh' },
     { nValue: 17000,
       scriptPubkeyLen: <Buffer 19>,
       scriptPubkey: <Buffer 76 a9 14 5b 79 a9 d2 9a 34 f2 f2 84 ec dd 33 00 9f fa 5e 02 52 b6 89 88 ac>,
       address: 'b1CosuxqSfN3uL8KyubTcHGDm4iVmCruQ7C',
       type: 'p2pkh' } ],
  s: 0,
  nVersion: <Buffer 02 00 00 00>,
  nbinput: 1,
  nboutput: 2,
  nLockTime: <Buffer 00 00 00 00> }
------------- End Check - deserialize 
------------- Check - verify 
Using standard signing
----- Transaction verified
----- Transaction hash: 9657fbb131ad4c41519fe231833ed6697dcdb8f906e508179a7e7ec4de03f9c5
------------- End Check - verify

**Comment by ianpurton** [comment] 2018-03-08 06:38
Also in the output you have transaction body and complete transaction, what is the difference?

Thanks

**Comment by Ayms** [comment] 2018-03-08 12:07
The difference is that 'complete transaction' is the one that you can send using the 'send' command directly to a node (btcp.suprnova.cc)

And 'transaction body' is the one that you must use if you send the transaction via an explorer

Like you are doing here, but we don't see it on the screenshot, if you used the 'complete transaction' then it's normal that it can't decode it, so probably the issue is here

I could do it but prefer that you send it yourself, please let me know

**Comment by ianpurton** [comment] 2018-03-08 12:51
Hi, I tried both actually. So I can confirm transaction body gave the TX decode failed 22.
![error](https://user-images.githubusercontent.com/36966/37151973-f2e145f2-22d7-11e8-95c1-c93427d7504c.PNG)

**Comment by ianpurton** [comment] 2018-03-08 13:07
I tried sending the complete transaction and got this output.

Version BTCP
Sending to btcp.suprnova.cc
Connected to : btcp.suprnova.cc:7933
Sent version to btcp.suprnova.cc
------ Answer receiced from btcp.suprnova.cc
version
verack
ping
getheaders
a8eaa2cd76657273696f6e000000000065000000b6703a5623bf02000100000000000000f334a15a00000000010000000000000000000000000000000000ffff23c3b847a772010000000000000000000000000000000000ffff91ef41171efd801a8b91cb4463b80f2f425443503a312e302e31302d312f434e040001a8eaa2cd76657261636b000000000000000000005df6e0e2a8eaa2cd70696e670000000000000000080000002f36fc2df36254f7d1fa97cea8eaa2cd676574686561646572730000e5030000ee01f7b823bf02001e6095af2dfe352f87a8cd593c0118d97c980dec12793616c2439eef8b000000003e00b8ac7e3697f35f10a188bf1c89051cc395eab2194719c5dbab3a01000000103fa658b3141c7d5193c60f78eccfbeff0a0d967042f76dccad533c000000000792668a83080b2984faeee8d251e6a3181e6e5d7c0eff6b7a680df500000000774712270582f53f6d81492ee0d8e35503810051ec3cac7260578c2201000000c3285f1db55eab0115d1cda780d43f143bddd4de803eea2c8fcc60fd000000004277afd4195ade6b167409cba3644620119e6b8a8ea4cb4e4606ddc2000000001df1428d478384828adbbe2ba51096a473741d5c0ddb2505cdd09f94000000004490ae1dab674cdd43ee309c7f6ab601a6442c3af4359cee71f10962000000005edf8861860bd63020282ef4f49d9f6a442a7f24c2d4bfcb72aac7fd000000007485872062e8c580681526fedd6cde99a12a4b8049488f9b52befbbe00000000dae9153a84d726fe6f831961769badbf625d5f86ba76339292c059db000000009e29733b06e0cbecbd49422dbf19df5a076048686157cbc2fdab5444010000001658be7cdbaec8abc7862d2143e2e4200abb32d36829f43a33c27a95000000006c9221e25c2b6b278b921bef2b3da46f332501d9bc700b932b852e76010000004cf440fb939bd25f8998281b1d6c8e804f0122237bd1bd9daef7274401000000cb864eaa5ca22927e7f0a0b9d8cfd46a28425805161b96b80744950d01000000bdf1f3cf1810bb802b3fa18768ecb3867ef80c46735f63597d4aacee000000005254b531524d3f888168acf3c010d7205d692495c7d4d7143e870b0d010000004a355684f2aee586275ea0656e4efd000351e76efcb8cd2b6d9c1dcd0000000013843336abdd7ba4e9a625d055c7a8ee8243be75121f1f5ef4916717000000002a69f5b6aa1895574a5a781f56b4d384e0fe8670b6f42a444108d1ed00000000ec69827a9262568045293f0d57362c7f53da0675d5c51fb58826f60e0e126a0037cb439bfc84622a8c3044c389f6bfa2601f269a9ee5d385992bfb7f361c8200550b99322f1d622e7b8de3ae6e0d6fab0e05b3e8d97da820db98a00300000000323f916cfe81904ae382fa61d667bdc029816bdeda55aee32a235304000000000a2db988b60a6244567ea367b1d3390603656f5acbbbef6681cd8dde09000000c71121f4749995eb62c4d36fffd12ffec457dafffbc633600230c7d700000000e3e595b26b5a9fb595ffdcc129c43422f59a4aafb86495b3e45c1d9c2a0000000206260143838b5ff52dc2eb7b4b8099d4e4c99dc3ef19794289a2cd4c1007000000000000000000000000000000000000000000000000000000000000000000
-------- Verack received - completing handshake with btcp.suprnova.cc
------ Sending transaction to btcp.suprnova.cc
Sent a8eaa2cd747800000000000000000000e10000009657fbb1020000000175031c53cfc21e9ee3966380b9adc4d991a8224c04f3d297a2b26e045b2d83db000000006a4730440220157fdca183bc7001fd7ac064706454cea8a120d65e17dced976b036b09447b6a022078bff8b4f280e91afee6ffa429f6ed0f9645b49b7d9499b6b734263338316637412103e131d6f9e9f83cfa18de2e89887cc4c829ab99c230bc884c22ddb6ffab19e121ffffffff028b5d0700000000001976a9143a48bfebcdc52c7b3831eab75a1955e58744c7e388ac68420000000000001976a9145b79a9d29a34f2f284ecdd33009ffa5e0252b68988ac00000000 to btcp.suprnova.cc
a8eaa2cd76657261636b000000000000000000005df6e0e2a8eaa2cd747800000000000000000000e10000009657fbb1020000000175031c53cfc21e9ee3966380b9adc4d991a8224c04f3d297a2b26e045b2d83db000000006a4730440220157fdca183bc7001fd7ac064706454cea8a120d65e17dced976b036b09447b6a022078bff8b4f280e91afee6ffa429f6ed0f9645b49b7d9499b6b734263338316637412103e131d6f9e9f83cfa18de2e89887cc4c829ab99c230bc884c22ddb6ffab19e121ffffffff028b5d0700000000001976a9143a48bfebcdc52c7b3831eab75a1955e58744c7e388ac68420000000000001976a9145b79a9d29a34f2f284ecdd33009ffa5e0252b68988ac00000000
End connection with btcp.suprnova.cc:7933

No errors, but looking at the blockchain the TX did not send. https://explorer.btcprivate.org/address/b1H4VhwWAoVGMqnXM8oqsKK2WzpMGkbRamm

**Comment by Ayms** [comment] 2018-03-08 15:14
I have already noticed that suprnova does not notify a reject when a tx is wrong

Apparently the version is not correct, I have modified it, please try with the latest tx.js

And please send the tx via the explorer

**Comment by Ayms** [comment] 2018-03-11 18:09
Then? What happened?

**Comment by ianpurton** [comment] 2018-03-12 09:36
I didn't re-test.

**Comment by Ayms** [comment] 2018-03-12 17:34
Are you planning to retry it? (if not please close the issue, some people succeeded to move their BTCP with the tool)

**Closed as completed** 2018-03-13 05:52 UTC
